name: ci

on: pull_request

jobs:
  setup:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18
      - name: Format
        run: gofmt -l .
      - name: Test
        run: go test -v ./...

